version: '3.6'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  postgres:
    # 10
    image: 'colovu/postgres:10'
    ports:
      - '5432:5432'
    container_name: postgres
    restart: always
    networks:
      - back-tier
    volumes:
      - $PWD/conf:/srv/conf
      - $PWD/log:/var/log
      - $PWD/datalog:/srv/datalog
      - $PWD/data:/srv/data
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=colovu
      - PG_DATABASE=postgres
      - ENV_DEBUG=yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge